-- Run on freshly initialized empty project tables to reproduce first-load evidence.
-- Do not relabel a later rerun as the first load. Existing evidence is retained.
USE SCHEMA CAPSTONE_23051560.SKILL_DEMAND;
CREATE TABLE IF NOT EXISTS COPY_AUDIT (phase VARCHAR,target VARCHAR,details VARIANT,recorded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP());
COPY INTO GOLD_SKILL_MONTH FROM @SKILL_DEMAND_STAGE FILES=('gold_skill_month.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'first','GOLD_SKILL_MONTH',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
COPY INTO GOLD_PAIR_MONTH FROM @SKILL_DEMAND_STAGE FILES=('gold_pair_month.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'first','GOLD_PAIR_MONTH',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
COPY INTO SILVER_POSTING_SKILL FROM @SKILL_DEMAND_STAGE FILES=('silver_posting_skill.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'first','SILVER_POSTING_SKILL',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
COPY INTO GOLD_SKILL_MONTH FROM @SKILL_DEMAND_STAGE FILES=('gold_skill_month.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'repeat','GOLD_SKILL_MONTH',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
COPY INTO GOLD_PAIR_MONTH FROM @SKILL_DEMAND_STAGE FILES=('gold_pair_month.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'repeat','GOLD_PAIR_MONTH',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
COPY INTO SILVER_POSTING_SKILL FROM @SKILL_DEMAND_STAGE FILES=('silver_posting_skill.csv') ON_ERROR=ABORT_STATEMENT;
INSERT INTO COPY_AUDIT(phase,target,details) SELECT 'repeat','SILVER_POSTING_SKILL',OBJECT_CONSTRUCT(*) FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
SELECT phase,target,details FROM COPY_AUDIT ORDER BY recorded_at;